version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.15.5
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enrollment.enabled: "true"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - lab-logging-network

  kibana:
    image: kibana:8.15.5
    container_name: kibana
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - lab-logging-network

networks:
  lab-logging-network:
    driver: bridge